### Create product1
POST http://localhost:8081/api/products
Content-Type: application/json
Accept: application/json

{
  "name": "product1",
  "description": "Description"
}

### Create product2
POST http://localhost:8081/api/products
Content-Type: application/json
Accept: application/json

{
  "name": "product2",
  "description": "Description"
}

### List products
GET http://localhost:8082/api/es/products
Accept: application/json

### Search product1
GET http://localhost:8082/api/es/products/search/findByNameLike/?name=product1
Accept: application/json

### Search product2
GET http://localhost:8082/api/es/products/search/findByNameLike/?name=product2
Accept: application/json
