### Create product
POST http://localhost:8081/api/products
Content-Type: application/json
Accept: application/json

{
  "name": "Product name",
  "description": "Product description"
}

### Get products
GET http://localhost:8081/api/products
Accept: application/json
